import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-poppins',
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>{children}</body>
    </html>
  );
}