name: verify

on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci # install node dependencies
      - run: npx tsc --noEmit # type check
      - run: npm run lint # linting
      - run: npm run build # building 